app:
  id: api-elc-invoice-lqpt
apollo:
  meta: http://10.213.4.50:8383
  bootstrap:
    namespaces: application,invoice.database,invoice.redis,invoice.global
    enabled: true
    eagerLoad:
      enabled: true